### ISSUE TITLE
Undeclared dependency on tornado

### ISSUE THREAD

**Issue by wolfgang42** [nytlabs/pageinfo#2]
I set up a python2 virtualenv and installed pageinfo, then tried importing it:

```
>>> import pageinfo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "venv2/lib/python2.7/site-packages/pageinfo/__init__.py", line 1, in <module>
    from pageinfo import get_meta
  File "venv2/lib/python2.7/site-packages/pageinfo/pageinfo.py", line 3, in <module>
    import tornado.httpclient
ImportError: No module named tornado.httpclient
```

`pip install tornado` fixes the problem, but this ought to be declared as a dependency.

**Comment by alexislloyd** [comment]
Pageinfo has been updated and is no longer dependent on tornado.

**Comment by mailbackwards** [comment]
When will version 0.4 be up on pip? I just pip installed the package and it's still on 0.35.

**Comment by alexislloyd** [comment]
Sorry, it's up now.
